import { TChampion } from "@compesn/shared/types/champion";

export const CHAMPIONS: TChampion[] = [
	{
		name: "Aatrox",
		fileName: "Aatrox",
		roles: ["top"],
		tags: ["Fighter"],
	},
	{
		name: "Ahri",
		fileName: "Ahri",
		roles: ["mid"],
		tags: ["Mage", "Assassin"],
	},
	{
		name: "Akali",
		fileName: "Akali",
		roles: ["top", "mid"],
		tags: ["Assassin"],
	},
	{
		name: "Akshan",
		fileName: "Akshan",
		roles: ["mid", "top"],
		tags: ["Marksman", "Assassin"],
	},
	{
		name: "Alistar",
		fileName: "Alistar",
		roles: ["support"],
		tags: ["Tank", "Support"],
	},
	{
		fileName: "Ambessa",
		name: "Ambessa",
		roles: ["top"],
		tags: ["Fighter", "Assassin"],
	},
	{
		name: "Amumu",
		fileName: "Amumu",
		roles: ["jungle", "support"],
		tags: ["Tank", "Support"],
	},
	{
		name: "Anivia",
		fileName: "Anivia",
		roles: ["mid"],
		tags: ["Mage"],
	},
	{
		name: "Annie",
		fileName: "Annie",
		roles: ["mid"],
		tags: ["Mage", "Support"],
	},
	{
		name: "Aphelios",
		fileName: "Aphelios",
		roles: ["bottom"],
		tags: ["Marksman"],
	},
	{
		name: "Ashe",
		fileName: "Ashe",
		roles: ["bottom", "support"],
		tags: ["Marksman", "Support"],
	},
	{
		name: "Aurelion Sol",
		fileName: "AurelionSol",
		roles: ["mid"],
		tags: ["Mage"],
	},
	{
		fileName: "Aurora",
		name: "Aurora",
		roles: ["mid", "top"],
		tags: ["Mage", "Assassin"],
	},
	{
		name: "Azir",
		fileName: "Azir",
		roles: ["mid"],
		tags: ["Mage", "Marksman"],
	},
	{
		name: "Bard",
		fileName: "Bard",
		roles: ["support"],
		tags: ["Support", "Mage"],
	},
	{
		name: "Bel'Veth",
		fileName: "Belveth",
		roles: ["jungle"],
		tags: ["Fighter"],
	},
	{
		name: "Blitzcrank",
		fileName: "Blitzcrank",
		roles: ["support"],
		tags: ["Tank", "Support"],
	},
	{
		name: "Brand",
		fileName: "Brand",
		roles: ["support"],
		tags: ["Mage", "Support"],
	},
	{
		name: "Braum",
		fileName: "Braum",
		roles: ["support"],
		tags: ["Tank", "Support"],
	},
	{
		name: "Briar",
		fileName: "Briar",
		roles: ["jungle"],
		tags: ["Fighter", "Assassin"],
	},
	{
		name: "Caitlyn",
		fileName: "Caitlyn",
		roles: ["bottom"],
		tags: ["Marksman"],
	},
	{
		name: "Camille",
		fileName: "Camille",
		roles: ["top"],
		tags: ["Fighter", "Assassin"],
	},
	{
		name: "Cassiopeia",
		fileName: "Cassiopeia",
		roles: ["mid"],
		tags: ["Mage"],
	},
	{
		name: "Cho'Gath",
		fileName: "Chogath",
		roles: ["top"],
		tags: ["Tank", "Mage"],
	},
	{
		name: "Corki",
		fileName: "Corki",
		roles: ["mid"],
		tags: ["Marksman", "Mage"],
	},
	{
		name: "Darius",
		fileName: "Darius",
		roles: ["top"],
		tags: ["Fighter", "Tank"],
	},
	{
		name: "Diana",
		fileName: "Diana",
		roles: ["jungle"],
		tags: ["Fighter", "Assassin"],
	},
	{
		name: "Dr. Mundo",
		fileName: "DrMundo",
		roles: ["top"],
		tags: ["Tank", "Fighter"],
	},
	{
		name: "Draven",
		fileName: "Draven",
		roles: ["bottom"],
		tags: ["Marksman"],
	},
	{
		name: "Ekko",
		fileName: "Ekko",
		roles: ["jungle", "mid"],
		tags: ["Assassin", "Mage"],
	},
	{
		name: "Elise",
		fileName: "Elise",
		roles: ["jungle"],
		tags: ["Assassin", "Mage"],
	},
	{
		name: "Evelynn",
		fileName: "Evelynn",
		roles: ["jungle"],
		tags: ["Assassin", "Mage"],
	},
	{
		name: "Ezreal",
		fileName: "Ezreal",
		roles: ["bottom"],
		tags: ["Marksman", "Mage"],
	},
	{
		name: "Fiddlesticks",
		fileName: "FiddleSticks",
		roles: ["jungle"],
		tags: ["Mage", "Support"],
	},
	{
		name: "Fiora",
		fileName: "Fiora",
		roles: ["top"],
		tags: ["Fighter", "Assassin"],
	},
	{
		name: "Fizz",
		fileName: "Fizz",
		roles: ["mid"],
		tags: ["Assassin", "Fighter"],
	},
	{
		name: "Galio",
		fileName: "Galio",
		roles: ["mid"],
		tags: ["Tank", "Mage"],
	},
	{
		name: "Gangplank",
		fileName: "Gangplank",
		roles: ["top", "mid"],
		tags: ["Fighter"],
	},
	{
		name: "Garen",
		fileName: "Garen",
		roles: ["top"],
		tags: ["Fighter", "Tank"],
	},
	{
		name: "Gnar",
		fileName: "Gnar",
		roles: ["top"],
		tags: ["Fighter", "Tank"],
	},
	{
		name: "Gragas",
		fileName: "Gragas",
		roles: ["top"],
		tags: ["Fighter", "Mage"],
	},
	{
		name: "Graves",
		fileName: "Graves",
		roles: ["jungle"],
		tags: ["Marksman"],
	},
	{
		name: "Gwen",
		fileName: "Gwen",
		roles: ["top"],
		tags: ["Fighter"],
	},
	{
		name: "Hecarim",
		fileName: "Hecarim",
		roles: ["jungle"],
		tags: ["Fighter", "Tank"],
	},
	{
		name: "Heimerdinger",
		fileName: "Heimerdinger",
		roles: ["mid"],
		tags: ["Mage", "Support"],
	},
	{
		fileName: "Hwei",
		name: "Hwei",
		roles: ["mid", "support"],
		tags: ["Mage", "Support"],
	},
	{
		name: "Illaoi",
		fileName: "Illaoi",
		roles: ["top"],
		tags: ["Fighter", "Tank"],
	},
	{
		name: "Irelia",
		fileName: "Irelia",
		roles: ["top", "mid"],
		tags: ["Fighter", "Assassin"],
	},
	{
		name: "Ivern",
		fileName: "Ivern",
		roles: ["jungle"],
		tags: ["Support", "Mage"],
	},
	{
		name: "Janna",
		fileName: "Janna",
		roles: ["support"],
		tags: ["Support", "Mage"],
	},
	{
		name: "Jarvan IV",
		fileName: "JarvanIV",
		roles: ["jungle"],
		tags: ["Fighter", "Tank"],
	},
	{ name: "Jax", fileName: "Jax", roles: ["top"], tags: ["Fighter"] },
	{
		name: "Jayce",
		fileName: "Jayce",
		roles: ["top", "mid"],
		tags: ["Fighter", "Marksman"],
	},
	{
		name: "Jhin",
		fileName: "Jhin",
		roles: ["bottom"],
		tags: ["Marksman", "Mage"],
	},
	{
		name: "Jinx",
		fileName: "Jinx",
		roles: ["bottom"],
		tags: ["Marksman"],
	},
	{
		name: "K'Sante",
		fileName: "KSante",
		roles: ["top", "mid"],
		tags: ["Tank", "Fighter"],
	},
	{
		name: "Kai'Sa",
		fileName: "Kaisa",
		roles: ["bottom"],
		tags: ["Marksman", "Mage"],
	},
	{
		name: "Kalista",
		fileName: "Kalista",
		roles: ["bottom"],
		tags: ["Marksman"],
	},
	{
		name: "Karma",
		fileName: "Karma",
		roles: ["support"],
		tags: ["Mage", "Support"],
	},
	{
		name: "Karthus",
		fileName: "Karthus",
		roles: ["jungle"],
		tags: ["Mage"],
	},
	{
		name: "Kassadin",
		fileName: "Kassadin",
		roles: ["mid"],
		tags: ["Assassin", "Mage"],
	},
	{
		name: "Katarina",
		fileName: "Katarina",
		roles: ["mid"],
		tags: ["Assassin", "Mage"],
	},
	{
		name: "Kayle",
		fileName: "Kayle",
		roles: ["top"],
		tags: ["Mage", "Marksman"],
	},
	{
		name: "Kayn",
		fileName: "Kayn",
		roles: ["jungle"],
		tags: ["Fighter", "Assassin"],
	},
	{
		name: "Kennen",
		fileName: "Kennen",
		roles: ["top"],
		tags: ["Mage"],
	},
	{
		name: "Kha'Zix",
		fileName: "Khazix",
		roles: ["jungle"],
		tags: ["Assassin"],
	},
	{
		name: "Kindred",
		fileName: "Kindred",
		roles: ["jungle"],
		tags: ["Marksman"],
	},
	{
		name: "Kled",
		fileName: "Kled",
		roles: ["top"],
		tags: ["Fighter"],
	},
	{
		name: "Kog'Maw",
		fileName: "KogMaw",
		roles: ["bottom"],
		tags: ["Marksman", "Mage"],
	},
	{
		name: "LeBlanc",
		fileName: "Leblanc",
		roles: ["mid"],
		tags: ["Assassin", "Mage"],
	},
	{
		name: "Lee Sin",
		fileName: "LeeSin",
		roles: ["jungle"],
		tags: ["Fighter", "Assassin"],
	},
	{
		name: "Leona",
		fileName: "Leona",
		roles: ["support"],
		tags: ["Tank", "Support"],
	},
	{
		name: "Lillia",
		fileName: "Lillia",
		roles: ["top", "jungle"],
		tags: ["Fighter", "Mage"],
	},
	{
		name: "Lissandra",
		fileName: "Lissandra",
		roles: ["mid"],
		tags: ["Mage"],
	},
	{
		name: "Lucian",
		fileName: "Lucian",
		roles: ["bottom"],
		tags: ["Marksman", "Assassin"],
	},
	{
		name: "Lulu",
		fileName: "Lulu",
		roles: ["support"],
		tags: ["Support", "Mage"],
	},
	{
		name: "Lux",
		fileName: "Lux",
		roles: ["mid", "support"],
		tags: ["Mage", "Support"],
	},
	{
		name: "Malphite",
		fileName: "Malphite",
		roles: ["top"],
		tags: ["Tank", "Mage"],
	},
	{
		name: "Malzahar",
		fileName: "Malzahar",
		roles: ["mid"],
		tags: ["Mage"],
	},
	{
		name: "Maokai",
		fileName: "Maokai",
		roles: ["support"],
		tags: ["Tank", "Support"],
	},
	{
		name: "Master Yi",
		fileName: "MasterYi",
		roles: ["jungle"],
		tags: ["Fighter", "Assassin"],
	},
	{
		fileName: "Mel",
		name: "Mel",
		roles: ["mid", "support"],
		tags: ["Mage", "Support"],
	},
	{
		name: "Milio",
		fileName: "Milio",
		roles: ["support"],
		tags: ["Support", "Mage"],
	},
	{
		name: "Miss Fortune",
		fileName: "MissFortune",
		roles: ["bottom", "support"],
		tags: ["Marksman", "Mage"],
	},
	{
		name: "Mordekaiser",
		fileName: "Mordekaiser",
		roles: ["top"],
		tags: ["Fighter", "Mage"],
	},
	{
		name: "Morgana",
		fileName: "Morgana",
		roles: ["support"],
		tags: ["Support", "Mage"],
	},
	{
		name: "Naafiri",
		fileName: "Naafiri",
		roles: ["top", "jungle", "mid"],
		tags: ["Assassin", "Fighter"],
	},
	{
		name: "Nami",
		fileName: "Nami",
		roles: ["support"],
		tags: ["Support", "Mage"],
	},
	{
		name: "Nasus",
		fileName: "Nasus",
		roles: ["top"],
		tags: ["Fighter", "Tank"],
	},
	{
		name: "Nautilus",
		fileName: "Nautilus",
		roles: ["support"],
		tags: ["Tank", "Support"],
	},
	{
		name: "Neeko",
		fileName: "Neeko",
		roles: ["mid"],
		tags: ["Mage", "Support"],
	},
	{
		name: "Nidalee",
		fileName: "Nidalee",
		roles: ["jungle"],
		tags: ["Assassin", "Mage"],
	},
	{
		name: "Nilah",
		fileName: "Nilah",
		roles: ["bottom"],
		tags: ["Fighter", "Assassin"],
	},
	{
		name: "Nocturne",
		fileName: "Nocturne",
		roles: ["jungle"],
		tags: ["Fighter", "Assassin"],
	},
	{
		name: "Nunu & Willump",
		fileName: "Nunu",
		roles: ["jungle"],
		tags: ["Tank", "Mage"],
	},
	{
		name: "Olaf",
		fileName: "Olaf",
		roles: ["top"],
		tags: ["Fighter", "Tank"],
	},
	{
		name: "Orianna",
		fileName: "Orianna",
		roles: ["mid"],
		tags: ["Mage", "Support"],
	},
	{ name: "Ornn", fileName: "Ornn", roles: ["top"], tags: ["Tank"] },
	{
		name: "Pantheon",
		fileName: "Pantheon",
		roles: ["jungle", "support"],
		tags: ["Fighter", "Assassin"],
	},
	{
		name: "Poppy",
		fileName: "Poppy",
		roles: ["jungle"],
		tags: ["Tank", "Fighter"],
	},
	{
		name: "Pyke",
		fileName: "Pyke",
		roles: ["support"],
		tags: ["Support", "Assassin"],
	},
	{
		name: "Qiyana",
		fileName: "Qiyana",
		roles: ["mid"],
		tags: ["Assassin"],
	},
	{
		name: "Quinn",
		fileName: "Quinn",
		roles: ["top"],
		tags: ["Marksman", "Assassin"],
	},
	{
		name: "Rakan",
		fileName: "Rakan",
		roles: ["support"],
		tags: ["Support"],
	},
	{
		name: "Rammus",
		fileName: "Rammus",
		roles: ["jungle"],
		tags: ["Tank"],
	},
	{
		name: "Rek'Sai",
		fileName: "RekSai",
		roles: ["jungle"],
		tags: ["Fighter", "Tank"],
	},
	{
		name: "Rell",
		fileName: "Rell",
		roles: ["support"],
		tags: ["Tank", "Support"],
	},
	{
		name: "Renata Glasc",
		fileName: "Renata",
		roles: ["support"],
		tags: ["Support", "Mage"],
	},
	{
		name: "Renekton",
		fileName: "Renekton",
		roles: ["top"],
		tags: ["Fighter", "Tank"],
	},
	{
		name: "Rengar",
		fileName: "Rengar",
		roles: ["jungle"],
		tags: ["Assassin", "Fighter"],
	},
	{
		name: "Riven",
		fileName: "Riven",
		roles: ["top"],
		tags: ["Fighter", "Assassin"],
	},
	{
		name: "Rumble",
		fileName: "Rumble",
		roles: ["top"],
		tags: ["Fighter", "Mage"],
	},
	{ name: "Ryze", fileName: "Ryze", roles: ["mid"], tags: ["Mage"] },
	{
		name: "Samira",
		fileName: "Samira",
		roles: ["bottom"],
		tags: ["Marksman", "Assassin"],
	},
	{
		name: "Sejuani",
		fileName: "Sejuani",
		roles: ["top", "jungle"],
		tags: ["Tank"],
	},
	{
		name: "Senna",
		fileName: "Senna",
		roles: ["support"],
		tags: ["Support", "Marksman"],
	},
	{
		name: "Seraphine",
		fileName: "Seraphine",
		roles: ["support"],
		tags: ["Support", "Mage"],
	},
	{
		name: "Sett",
		fileName: "Sett",
		roles: ["top"],
		tags: ["Fighter", "Tank"],
	},
	{
		name: "Shaco",
		fileName: "Shaco",
		roles: ["jungle"],
		tags: ["Assassin"],
	},
	{ name: "Shen", fileName: "Shen", roles: ["top"], tags: ["Tank"] },
	{
		name: "Shyvana",
		fileName: "Shyvana",
		roles: ["top", "jungle"],
		tags: ["Fighter", "Mage"],
	},
	{
		name: "Singed",
		fileName: "Singed",
		roles: ["top"],
		tags: ["Tank", "Mage"],
	},
	{
		name: "Sion",
		fileName: "Sion",
		roles: ["top"],
		tags: ["Tank", "Fighter"],
	},
	{
		name: "Sivir",
		fileName: "Sivir",
		roles: ["bottom"],
		tags: ["Marksman"],
	},
	{
		name: "Skarner",
		fileName: "Skarner",
		roles: ["jungle"],
		tags: ["Tank", "Fighter"],
	},
	{
		fileName: "Smolder",
		name: "Smolder",
		roles: ["mid", "bottom"],
		tags: ["Marksman", "Mage"],
	},
	{
		name: "Sona",
		fileName: "Sona",
		roles: ["support"],
		tags: ["Support", "Mage"],
	},
	{
		name: "Soraka",
		fileName: "Soraka",
		roles: ["support"],
		tags: ["Support", "Mage"],
	},
	{
		name: "Swain",
		fileName: "Swain",
		roles: ["mid", "support"],
		tags: ["Mage", "Support"],
	},
	{
		name: "Sylas",
		fileName: "Sylas",
		roles: ["mid"],
		tags: ["Mage", "Assassin"],
	},
	{
		name: "Syndra",
		fileName: "Syndra",
		roles: ["mid"],
		tags: ["Mage"],
	},
	{
		name: "Tahm Kench",
		fileName: "TahmKench",
		roles: ["top"],
		tags: ["Tank", "Support"],
	},
	{
		name: "Taliyah",
		fileName: "Taliyah",
		roles: ["jungle", "mid"],
		tags: ["Mage", "Support"],
	},
	{
		name: "Talon",
		fileName: "Talon",
		roles: ["jungle", "mid"],
		tags: ["Assassin"],
	},
	{
		name: "Taric",
		fileName: "Taric",
		roles: ["support"],
		tags: ["Support", "Tank"],
	},
	{
		name: "Teemo",
		fileName: "Teemo",
		roles: ["top"],
		tags: ["Marksman", "Mage"],
	},
	{
		name: "Thresh",
		fileName: "Thresh",
		roles: ["support"],
		tags: ["Support", "Tank"],
	},
	{
		name: "Tristana",
		fileName: "Tristana",
		roles: ["bottom"],
		tags: ["Marksman", "Assassin"],
	},
	{
		name: "Trundle",
		fileName: "Trundle",
		roles: ["jungle"],
		tags: ["Fighter", "Tank"],
	},
	{
		name: "Tryndamere",
		fileName: "Tryndamere",
		roles: ["top"],
		tags: ["Fighter", "Assassin"],
	},
	{
		name: "Twisted Fate",
		fileName: "TwistedFate",
		roles: ["mid"],
		tags: ["Mage", "Marksman"],
	},
	{
		name: "Twitch",
		fileName: "Twitch",
		roles: ["bottom"],
		tags: ["Marksman", "Assassin"],
	},
	{
		name: "Udyr",
		fileName: "Udyr",
		roles: ["jungle"],
		tags: ["Fighter", "Tank"],
	},
	{
		name: "Urgot",
		fileName: "Urgot",
		roles: ["top"],
		tags: ["Fighter", "Tank"],
	},
	{
		name: "Varus",
		fileName: "Varus",
		roles: ["bottom"],
		tags: ["Marksman", "Mage"],
	},
	{
		name: "Vayne",
		fileName: "Vayne",
		roles: ["top", "bottom"],
		tags: ["Marksman", "Assassin"],
	},
	{
		name: "Veigar",
		fileName: "Veigar",
		roles: ["mid"],
		tags: ["Mage"],
	},
	{
		name: "Vel'Koz",
		fileName: "Velkoz",
		roles: ["support"],
		tags: ["Mage", "Support"],
	},
	{ name: "Vex", fileName: "Vex", roles: ["mid"], tags: ["Mage"] },
	{
		name: "Vi",
		fileName: "Vi",
		roles: ["jungle"],
		tags: ["Fighter", "Assassin"],
	},
	{
		name: "Viego",
		fileName: "Viego",
		roles: ["jungle"],
		tags: ["Fighter", "Assassin"],
	},
	{
		name: "Viktor",
		fileName: "Viktor",
		roles: ["mid"],
		tags: ["Mage"],
	},
	{
		name: "Vladimir",
		fileName: "Vladimir",
		roles: ["mid"],
		tags: ["Mage", "Fighter"],
	},
	{
		name: "Volibear",
		fileName: "Volibear",
		roles: ["top", "jungle"],
		tags: ["Fighter", "Tank"],
	},
	{
		name: "Warwick",
		fileName: "Warwick",
		roles: ["jungle"],
		tags: ["Fighter", "Tank"],
	},
	{
		name: "Wukong",
		fileName: "MonkeyKing",
		roles: ["top", "jungle"],
		tags: ["Fighter", "Tank"],
	},
	{
		name: "Xayah",
		fileName: "Xayah",
		roles: ["bottom"],
		tags: ["Marksman"],
	},
	{
		name: "Xerath",
		fileName: "Xerath",
		roles: ["mid", "support"],
		tags: ["Mage", "Support"],
	},
	{
		name: "Xin Zhao",
		fileName: "XinZhao",
		roles: ["jungle"],
		tags: ["Fighter", "Tank"],
	},
	{
		name: "Yasuo",
		fileName: "Yasuo",
		roles: ["top", "mid", "bottom"],
		tags: ["Fighter", "Assassin"],
	},
	{
		name: "Yone",
		fileName: "Yone",
		roles: ["top", "mid"],
		tags: ["Fighter", "Assassin"],
	},
	{
		name: "Yorick",
		fileName: "Yorick",
		roles: ["top"],
		tags: ["Fighter", "Tank"],
	},
	{
		fileName: "Yunara",
		name: "Yunara",
		roles: [],
		tags: ["Marksman"],
	},
	{
		name: "Yuumi",
		fileName: "Yuumi",
		roles: ["support"],
		tags: ["Support", "Mage"],
	},
	{
		name: "Zac",
		fileName: "Zac",
		roles: ["jungle"],
		tags: ["Tank", "Fighter"],
	},
	{
		name: "Zed",
		fileName: "Zed",
		roles: ["jungle", "mid"],
		tags: ["Assassin"],
	},
	{
		name: "Zeri",
		fileName: "Zeri",
		roles: ["bottom"],
		tags: ["Marksman"],
	},
	{
		name: "Ziggs",
		fileName: "Ziggs",
		roles: ["mid", "bottom"],
		tags: ["Mage"],
	},
	{
		name: "Zilean",
		fileName: "Zilean",
		roles: ["support"],
		tags: ["Support", "Mage"],
	},
	{ name: "Zoe", fileName: "Zoe", roles: ["mid"], tags: ["Mage"] },
	{
		name: "Zyra",
		fileName: "Zyra",
		roles: ["support"],
		tags: ["Mage", "Support"],
	},
];
